const assert = require('assert');
const {ContextCompileController, contextCompileUserMessage, reviewProgress, nextPendingCandidate} = require('../gaia/static/context_compile_controller.js');
const response = (body, ok=true, status=ok ? 202 : 500) => ({ok, status, json: async()=>body});
(async()=>{
  let workspace='A', rendered=[], messages=[], calls=[];
  const queue=[response({job_id:'old',status_url:'/old'}), response({status:'running',message:'Собираем контекст: фрагмент 1 из 2…'}), response({job_id:'new',status_url:'/new'}), response({status:'done',message:'Контекст собран. Проверьте кандидатов.',result:{candidates:[{title:'B'}]}})];
  const controller=new ContextCompileController({workspace:()=>workspace,render:x=>rendered=x,message:(x,e)=>messages.push([x,e]),delay:async()=>{workspace='B';controller.changeWorkspace();},fetchImpl:async(url)=>{calls.push(url);return queue.shift();}});
  await controller.start('sanA'); assert.deepStrictEqual(rendered,[]); assert.strictEqual(controller.jobId,'');
  await controller.start('sanB'); assert.deepStrictEqual(rendered,[{title:'B'}]); assert.ok(!JSON.stringify(messages).includes('old'));
  assert.ok(calls.some(x=>x==='/new'));
  let cancelCall=''; const cancelling=new ContextCompileController({workspace:()=>workspace,render:()=>{},message:()=>{},fetchImpl:async url=>{cancelCall=url;return response({});}}); cancelling.jobId='job-safe'; assert.strictEqual(await cancelling.cancel(),true); assert.strictEqual(cancelCall,'/api/jobs/job-safe/cancel');
  let lateCancelCall=''; let lateMessage=''; const finalizing=new ContextCompileController({workspace:()=>workspace,render:()=>{},message:x=>lateMessage=x,fetchImpl:async url=>{lateCancelCall=url;return response({});}}); finalizing.jobId='job-finalizing'; finalizing.phase='finalizing'; assert.strictEqual(await finalizing.cancel(),false); assert.strictEqual(lateCancelCall,''); assert.strictEqual(lateMessage,'Сохранение контекста уже завершается. Дождитесь результата.');
  const diagnostics=[]; const states=[]; const failureCase=async(fetchImpl, expectedCode, expectedMessage)=>{ const messages=[]; const controller=new ContextCompileController({workspace:()=>workspace,render:()=>{},message:(message)=>messages.push(message),state:state=>states.push(state),fetchImpl,onDiagnostic:(event,fields)=>diagnostics.push([event,fields])}); assert.strictEqual(await controller.start('artifact-never-logged'),false); assert.strictEqual(controller.jobId,''); assert.strictEqual(controller.phase,''); assert.strictEqual(messages.at(-1),expectedMessage); assert.strictEqual(diagnostics.at(-1)[0],'request_failed'); assert.strictEqual(diagnostics.at(-1)[1].error_code,expectedCode); assert.ok(!JSON.stringify(diagnostics.at(-1)).includes('artifact-never-logged')); };
  let receiverCalls=0; const receiver={fetch(url){ if(this!==receiver) throw new TypeError('wrong receiver'); receiverCalls++; return Promise.resolve(url==='/receiver-job' ? response({status:'done',result:{candidates:[]}}) : response({job_id:'receiver-job',status_url:'/receiver-job'})); }};
  await failureCase(receiver.fetch, 'request_invocation_failed', 'Не удалось запустить запрос сборки контекста. Перезапустите Gaia и повторите действие.');
  const receiverDiagnostics=[]; const bound=new ContextCompileController({workspace:()=>workspace,render:()=>{},message:()=>{},fetchImpl:receiver.fetch.bind(receiver),onDiagnostic:(event,fields)=>receiverDiagnostics.push([event,fields])}); await bound.start('receiver-artifact'); assert.ok(receiverCalls>=2); assert.ok(receiverDiagnostics.some(([event,fields])=>event==='request_succeeded' && fields.http_status===202));
  await failureCase(()=>Promise.reject(new Error('network')), 'request_rejected', 'Не удалось связаться с локальным сервисом Gaia. Проверьте, что приложение готово к работе.');
  await failureCase(()=>response({},false,403), 'http_rejected', 'Не удалось начать сборку проектного контекста. Данные не изменены.');
  await failureCase(()=>({ok:true,status:202,json:async()=>{throw new Error('bad json');}}), 'invalid_response', 'Не удалось начать сборку проектного контекста. Данные не изменены.');
  await failureCase(()=>response({},true,202), 'invalid_job_contract', 'Не удалось начать сборку проектного контекста. Данные не изменены.');
  assert.ok(states.filter(state=>state==='error').length>=5);
  assert.strictEqual(contextCompileUserMessage({status:'failed',user_message:'internal'}), 'Не удалось завершить сборку проектного контекста. Контекст не изменён.');
  assert.strictEqual(contextCompileUserMessage({status:'complete_empty'}), 'Сборка завершена успешно, но элементов проектного контекста не найдено.');
  const reviewSet=[{id:'confirmed',status:'confirmed'},{id:'pending-a',status:'pending'},{id:'rejected',status:'rejected'},{id:'pending-b',status:'duplicate'},{id:'old',status:'pending',current:false}];
  assert.deepStrictEqual(reviewProgress(reviewSet),{total:4,processed:2,pending:2});
  assert.strictEqual(nextPendingCandidate(reviewSet).id,'pending-a');
  assert.deepStrictEqual(reviewProgress([{id:'done',status:'confirmed'}]),{total:1,processed:1,pending:0});
  assert.strictEqual(nextPendingCandidate([{id:'done',status:'confirmed'}]),null);
  const resumedCalls=[]; const resumedStates=[]; const resumed=new ContextCompileController({workspace:()=>workspace,render:()=>{},message:()=>{},state:(status)=>resumedStates.push(status),delay:async()=>{},fetchImpl:async(url)=>{resumedCalls.push(url);return response({status:'done',result:{candidates:[]}});}});
  await resumed.resume('existing-job','/api/jobs/existing-job',{status:'running',phase:'compiling'}); assert.deepStrictEqual(resumedCalls,['/api/jobs/existing-job']); assert.deepStrictEqual(resumedStates,['running','done']);
  const interruptedCalls=[]; const interrupted=new ContextCompileController({workspace:()=>workspace,render:()=>{},message:()=>{},delay:async()=>{throw new Error('must not poll twice');},fetchImpl:async(url)=>{interruptedCalls.push(url);return interruptedCalls.length===1?response({job_id:'interrupted-job',status_url:'/api/jobs/interrupted-job'}):response({status:'interrupted'});}});
  await interrupted.start('artifact-interrupted'); assert.deepStrictEqual(interruptedCalls,['/api/context/artifact-interrupted/compile','/api/jobs/interrupted-job']); assert.strictEqual(interrupted.jobId,'');
  console.log('context compile controller checks passed');
})().catch(error=>{console.error(error);process.exit(1);});
