"""Safely diagnose local Ollama context-extraction compatibility.

The script deliberately reports only aggregate protocol and validation metrics.
It never writes prompts or model responses to the repository.
"""
from __future__ import annotations

import argparse
import json
import tempfile
import time
import urllib.request
from pathlib import Path
from unittest.mock import patch

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from gaia.context_compiler import ContextCompiler, context_response_schema, local_context_model, validate_candidates
from gaia.local_llm import local_llm_payload, response_content
from gaia.protection import protect
from gaia.provenance import ProvenanceStore
from gaia.review import ReviewService

ENDPOINT = "http://127.0.0.1:11434"
MODELS = {
    "qwen3.5:9b": {"num_ctx": 32768, "think": False},
    "qwen3:14b": {"num_ctx": 16384, "think": False},
    "gpt-oss:20b": {"num_ctx": 16384, "think": "low"},
}
SIMPLE_SCHEMA = {
    "type": "object", "properties": {"candidates": {"type": "array", "items": {
        "type": "object", "properties": {
            "type": {"enum": ["requirement", "decision", "risk", "open_question", "action"]},
            "title": {"type": "string"}, "statement": {"type": "string"},
            "block": {"type": "object", "properties": {"start": {"type": "integer"}, "end": {"type": "integer"}}, "required": ["start", "end"], "additionalProperties": False},
            "confidence": {"enum": ["low", "medium", "high"]}, "requires_review": {"const": True},
        }, "required": ["type", "title", "statement", "block", "confidence", "requires_review"], "additionalProperties": False,
    }}}, "required": ["candidates"], "additionalProperties": False,
}
POSITIVE = "\n\n".join((
    "Действие: [Координатор-Север] должен согласовать список помещений до 15 сентября 2026 года. Статус: назначено. Приоритет: высокий.",
    "Решение: владельцем процесса назначен [Координатор-Орбита].",
    "Требование: еженедельный отчёт должен быть подготовлен до 1 октября 2026 года.",
    "Риск: возможна задержка поставки. Ответственный за контроль: [Инженер-Север].",
))
NEGATIVE = "\n\n".join((
    "Действие: необходимо подготовить отчёт.",
    "Риск: возможна задержка поставки.",
    "Решение: использовать локальное хранение.",
))


def production_contract() -> tuple[str, dict]:
    """Capture the exact prompt/schema generated by the production function."""
    captured: dict = {}

    def capture(prompt, timeout, system, **kwargs):
        captured.update(prompt=prompt, schema=kwargs["response_schema"])
        return {"ok": True, "answer": '{"candidates":[]}'}

    with patch("gaia.module_assist.call_lm_studio_with_deadline", side_effect=capture):
        local_context_model("контроль")
    return captured["prompt"].replace("контроль", "{material}"), captured["schema"]


def post(path: str, payload: dict, timeout: int = 180) -> tuple[int, dict]:
    request = urllib.request.Request(
        ENDPOINT + path, data=json.dumps(payload, ensure_ascii=False).encode(),
        headers={"Content-Type": "application/json"}, method="POST",
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.status, json.loads(response.read().decode())


def metadata(items: list[dict], positive: bool) -> dict[str, bool]:
    by_type = {item.get("item_type"): item for item in items}
    action = by_type.get("action", {})
    return {
        "actor_ref": bool(action.get("actor_ref")) if positive else any(bool(item.get("actor_ref")) for item in items),
        "deadline": bool(action.get("deadline")) if positive else any(bool(item.get("deadline")) for item in items),
        "status": bool(action.get("explicit_status")) if positive else any(bool(item.get("explicit_status")) for item in items),
        "priority": bool(action.get("priority")) if positive else any(bool(item.get("priority")) for item in items),
    }


def compiler_result(payload: dict, material: str) -> tuple[int, dict[str, bool], str]:
    try:
        parsed = validate_candidates(payload, len(material), 16)
    except Exception as exc:
        return 0, {key: False for key in ("actor_ref", "deadline", "status", "priority")}, type(exc).__name__
    with tempfile.TemporaryDirectory() as folder:
        store = ProvenanceStore(Path(folder) / "storage")
        workspace = store.create_workspace()
        source = store.accept_bytes(workspace, material.encode(), "text/plain")
        extraction = store.create_extraction(workspace, source["source_id"], "diagnostic")
        sanitized = protect(store, workspace, extraction["artifact_id"])["sanitized"]
        review = ReviewService(store, workspace, lambda _: {"status": "completed", "findings": []})
        review.start(sanitized["artifact_id"]); review.confirm(sanitized["artifact_id"])
        items = ContextCompiler(store, workspace, lambda _: {"candidates": parsed}).compile(sanitized["artifact_id"])
        return len(items), metadata(items, material == POSITIVE), ""


def run_one(model: str, mode: str, material: str, prompt_template: str, schema: dict, endpoint: str) -> dict:
    profile = MODELS[model]
    provider = {"type": "ollama", "thinking": profile["think"], "json_mode": True}
    chosen_schema = schema if mode in {"schema", "schema_prompt"} else (SIMPLE_SCHEMA if mode == "simple_schema" else None)
    prompt = prompt_template.replace("{material}", material)
    if mode == "schema_prompt": prompt += "\nСхема: candidates содержит только тип, заголовок, утверждение, block, confidence, requires_review и явно названные optional metadata."
    system = "Ты локальный компилятор проектного контекста Gaia."
    payload = local_llm_payload(provider, model, system, prompt, 0, max_tokens=2400, context_length=profile["num_ctx"], response_schema=chosen_schema)
    if mode == "json": payload["format"] = "json"
    if endpoint == "generate":
        payload = {"model": model, "prompt": prompt, "system": system, "stream": False, "think": profile["think"], "options": payload["options"], "format": payload["format"]}
    started = time.monotonic()
    result = {"model": model, "endpoint": "/api/" + endpoint, "format_mode": "schema" if chosen_schema else "json", "think_mode": profile["think"], "http_status": None, "response_chars": 0, "thinking_chars": 0, "done": False, "done_reason": "", "prompt_eval_count": None, "eval_count": None, "duration_ms": 0, "json_parse": "not_run", "schema_validation": "not_run", "candidates_json": 0, "candidates_backend": 0, "candidates_compiler": 0, "actor_ref": False, "deadline": False, "status": False, "priority": False, "error_code": ""}
    try:
        status, raw = post("/api/" + endpoint, payload)
        answer = response_content(provider, raw) if endpoint == "chat" else str(raw.get("response") or "")
        thinking = raw.get("message", {}).get("thinking") if endpoint == "chat" else raw.get("thinking")
        result.update(http_status=status, response_chars=len(answer), thinking_chars=len(str(thinking or "")), done=bool(raw.get("done")), done_reason=str(raw.get("done_reason") or ""), prompt_eval_count=raw.get("prompt_eval_count"), eval_count=raw.get("eval_count"))
        parsed = json.loads(answer); result["json_parse"] = "ok"; result["candidates_json"] = len(parsed.get("candidates", [])) if isinstance(parsed, dict) else 0
        validated = validate_candidates(parsed, len(material), 16); result["schema_validation"] = "ok"; result["candidates_backend"] = len(validated)
        count, flags, error = compiler_result(parsed, material); result["candidates_compiler"] = count; result.update(flags); result["error_code"] = error
    except Exception as exc:
        result["error_code"] = type(exc).__name__
    result["duration_ms"] = round((time.monotonic() - started) * 1000)
    return result


def unload(model: str) -> None:
    try:
        post("/api/generate", {"model": model, "prompt": "", "stream": False, "keep_alive": 0}, timeout=30)
    except Exception:
        pass


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", choices=MODELS, action="append")
    parser.add_argument("--mode", choices=("schema", "schema_prompt", "json", "simple_schema"), action="append")
    parser.add_argument("--negative", action="store_true")
    parser.add_argument("--endpoint", choices=("chat", "generate"), default="chat")
    args = parser.parse_args()
    prompt, schema = production_contract()
    material = NEGATIVE if args.negative else POSITIVE
    models = args.model or list(MODELS)
    modes = args.mode or ["schema", "schema_prompt", "json", "simple_schema"]
    results = []
    for model in models:
        for mode in modes:
            item = run_one(model, mode, material, prompt, schema, args.endpoint)
            item["mode"] = mode; item["control"] = "negative" if args.negative else "positive"
            print(json.dumps(item, ensure_ascii=False, sort_keys=True))
            results.append(item)
        unload(model)
    if args.negative:
        return 0 if any(row["candidates_compiler"] and not any(row[key] for key in ("actor_ref", "deadline", "status", "priority")) for row in results) else 1
    return 0 if any(row["candidates_compiler"] >= 4 and all(row[key] for key in ("actor_ref", "deadline", "status", "priority")) for row in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
